export const SEO_KEYWORDS = {
    recruitment: [
        "applicant tracking system", "applicant tracking software", "candidate tracking system",
        "candidate relationship management systems", "ats tracking system", "ats applicant tracking system",
        "ats in talent acquisition", "recruitment tracker google sheet", "best applicant tracking",
        "logistics tracking systems", "beating the ats", "user tracking system", "google applicant tracking system",
        "attendance and leave management software", "tracking system open source", "applicant tracking system in hr",
        "attendance management system application", "advanced tracking systems", "list of applicant tracking software",
        "beating ats", "job applicant tracking", "online ats system", "free referral tracking system",
        "taleo ats system", "cv automatic tracking system", "tracking system website", "open source ats software",
        "recruiter ats systems", "automated applicant tracking systems", "online tracking software",
        "applicant tracking tools", "greenhouse ats price", "opencats ats", "ats software", "smart tracking system",
        "ats crm systems", "ats resume tracking system", "zoho recruit ats", "event tracking system",
        "hr candidate tracking system", "breezy hr software", "ats in recruitment process", "greenhouse ats features",
        "hour tracking system", "free applicant tracking system software", "application tracking system in recruitment",
        "digital tracking system", "applicant tracking system github", "recruitment software ats",
        "free ats software for recruiters", "icims system", "applicant tracking system features", "common ats",
        "ats use", "ats hr tools", "ats vendors", "medical representative tracking system",
        "office file tracking system", "applicant software", "most common ats systems",
        "small business job tracking software", "applicant tracking systems atss", "ats job", "ats uses",
        "attendance management system web application", "time tracking bamboohr", "recruitment ats tools",
        "beating ats resume", "applicant tracking system greenhouse", "resume tracking system free",
        "zoho applicant tracking system", "best applicant tracking systems for small companies",
        "building an applicant tracking system", "forklift tracking system", "file tracking system",
        "human resource tracking system", "ats hiring system", "cats applicant tracking", "cats tracking system",
        "cheapest recruiting software", "ats for hr", "breezy hr ats", "applicant tracking systems ats free online",
        "fasttrack schedule software", "applicant tracking software for recruiters", "hr ats software",
        "ai applicant tracking software", "free ats software online", "ats open source", "free applicant tracking",
        "best ats applicant tracking system", "applicant tracking and recruiting software",
        "applicant tracking programs", "ats free software", "applicant tracking software ats", "ats system hr",
        "free visitor management system open source", "applicant tracking software for staffing agencies",
        "recruitment tracker dashboard", "job applicant tracking software", "best recruitment software sri lanka",
        "applicant tracking system for smes colombo", "automated cv parsing sri lanka", "whatsapp recruitment tool sri lanka",
        // Extended high-intent keywords
        "enterprise ats solution sri lanka", "cloud based recruitment platform negombo", "ai recruitment software seeduwa",
        "talent management system sri lanka", "human resource information system hris sri lanka",
        "automated payroll and attendance system seeduwa", "employee portal development negombo",
        "smart hiring tools sri lanka", "cv parsing engine integration", "recruitment analytics dashboard",
        "digital hr transformation sri lanka", "modern hr tech stack colombo", "hr automation for hospitality sri lanka"
    ],
    tier1: [
        // Standard Enterprise & SaaS
        "Custom AI & Agentic Software", "Autonomous AI agent development", "Enterprise agentic workflows",
        "Bespoke AI software solutions", "Multi-agent system architecture", "AI agent security frameworks",
        "Generative AI for enterprise", "Custom LLM fine-tuning services", "Autonomous digital employees",
        "AI-driven business process automation", "Goal-oriented AI agents", "AI agent pilot-to-production",
        "Scalable agentic commerce", "Agentic orchestration mesh", "Enterprise AI strategy consulting",
        "Custom AI chatbot for high-end retail", "AI-led legacy modernization", "Predictive maintenance AI agents",
        "AI-native software architecture", "Autonomous customer concierge", "B2B sales automation agents",
        "AI agent knowledge base grounding", "Secure AI implementation", "Global AI-powered data analytics dashboards",
        "Cognitive automation services", "Advanced RAG implementation",

        // Next-Gen Mobile & Web
        "Next.js 16 enterprise development", "React Native New Architecture migration", "High-performance cross-platform apps",
        "Fabric renderer optimization", "TurboModules implementation", "Next.js PPR for e-commerce",
        "Server-side rendering mobile apps", "React Native JSI C++ development", "Universal app engineering",
        "Zero-bridge React Native apps", "Scalable SaaS dashboard", "Next.js Enterprise mobile security standards",
        "Custom visionOS spatial apps", "Next.js Turbopack build optimization", "React Native shadow tree optimization",
        "Multi-tenant SaaS architecture", "Next.js 16 developer for hire", "Performance-first mobile engineering",
        "Progressive Web Apps enterprise", "Cloud-native mobile backends",

        // Custom Software & Outsourcing
        "Custom software development 2026", "Offshore AI engineering team", "Global Capability Center as a Service",
        "Build-Operate-Transfer software model", "Bespoke ERP development", "Digital sovereignty cloud solutions",
        "Intelligent process automation", "Custom CRM for regulated industries", "Legacy system digital transformation",
        "Outcome-based software contracts", "Software staff augmentation AI", "Enterprise-grade low-code integration",
        "Resilient digital architecture", "Agile software development global", "Full-stack engineering services",
        "Cloud migration for enterprise", "API-first software development", "Dedicated software development team",
        "Custom fintech software solutions", "Microservices architecture design"
    ],
    tier2: [
        // Local Business & AI Automation
        "Business automation software Sri Lanka", "AI solutions for Sri Lankan corporates", "Enterprise AI company Colombo",
        "Custom AI software development Sri Lanka", "Sera Auto business automation", "SME digital transformation Sri Lanka",
        "AI for Sri Lankan banking and finance", "Digital modernization services Colombo", "AI-powered customer support Sri Lanka",
        "Automated accounting software Sri Lanka", "Data-driven decision making tools SL", "Sri Lanka AI strategy partners",
        "Top ICT company in Sri Lanka", "AI for Sri Lankan manufacturing sector", "Corporate AI training and implementation",

        // Local Mobile & Software Development
        "Mobile app development Sri Lanka", "Best mobile app company Colombo", "Android and iOS developers Sri Lanka",
        "React Native app development Colombo", "Next.js developer Sri Lanka", "Custom software company Sri Lanka",
        "Enterprise mobile apps Colombo", "E-commerce app development Sri Lanka", "Mobile banking app security SL",
        "Fintech app developers Sri Lanka", "Custom CRM software Sri Lanka", "HR management system Sri Lanka",
        "Payroll software Sri Lanka", "ERP system development Sri Lanka", "Inventory management software SL",
        "Web application development Colombo", "Software outsourcing Sri Lanka", "IT consulting services Colombo",
        "PDPA compliant software development SL", "Cloud migration services Sri Lanka",
        "Software company Seeduwa", "Software company Negombo", "Web development Seeduwa", "Web development Negombo",
        "Best IT company Seeduwa", "Custom software Negombo", "AI solutions Seeduwa",
        "AI Applicant Tracking System Sri Lanka", "Custom Recruitment Software Seeduwa", "ATS for businesses Negombo", "Automated Hiring Platform Sri Lanka"
    ],
    authority: [
        // International SEO & Authority
        "Generative Engine Optimization services", "Optimize website for AI Overviews", "AI citation authority branding",
        "Rank in ChatGPT search 2026", "Structured data for AI agent crawling", "AI-first content marketing",
        "Voice search optimization enterprise", "Technical SEO for agentic discovery", "Conversational keyword research",
        "Brand presence in AI search", "LLM citation and referral optimization", "Semantic mapping for search",
        "GEO strategy for software firms", "Predictive SEO analytics", "Automated SEO audit AI agents"
    ],
    // Web Development Core Keywords
    webDev: [
        // Core Industry Keywords
        "Web development company", "Web development services", "Custom web development",
        "Web application development", "Website design and development", "Website developer",
        "Web design agency", "Professional web development", "Full-service web development",
        "Web development firm", "Web development solutions",

        // Service-Specific & Technology
        "Ecommerce web development company", "Responsive web design", "Frontend development",
        "Backend developer", "WordPress website creation", "Shopify web design agency",
        "Progressive Web Application PWA", "React web development", "Node.js web development",
        "Custom ecommerce development", "Headless CMS development", "JAMstack development services",
        "TypeScript development company", "Tailwind CSS development", "UI UX design services",
        "Single page application development",

        // Long-Tail & High-Intent
        "Best web design company", "Custom software development services", "Hire web developers",
        "Website maintenance services", "API development company", "Best web development agency near me",
        "Affordable web development services", "Enterprise web application development",
        "Custom website design for startups", "E-commerce website development cost",
        "Web development company for small business", "Web application security services",
        "Website redesign services", "Landing page design services", "Web development consultation",
        "Full stack web developer for hire", "Website performance optimization services",
        "Cross-platform web development", "Cloud-based web application development",
        "SaaS web application development", "Web development outsourcing company",
    ],
    generated: [
        "AI-powered logistics optimization", "Neural network consulting", "Deep learning for healthcare",
        "Computer vision systems integration", "Natural language processing for legal tech", "AI ethics compliance auditing",
        "Automated code generation tools", "Self-healing infrastructure automation", "AI-driven supply chain resilience",
        "Hyper-personalized marketing AI", "Robotic Process Automation (RPA) 2.0", "Edge AI implementation services",
        "Federated learning solutions", "Explainable AI (XAI) consulting", "AI model governance frameworks",
        "Synthetic data generation for training", "Digital twin development services", "Smart city AI infrastructure",
        "Precision agriculture AI solutions", "AI-enhanced cybersecurity defense", "Quantum-resistant cryptography integration",
        "Blockchain-AI convergence solutions", "Decentralized AI marketplaces", "Web3 autonomous organizations (DAOs)",
        "Metaverse enterprise solutions", "Immersive commerce experiences", "Haptic technology integration",
        "Brain-computer interface (BCI) apps", "Neuromorphic computing software", "Bioinformatics data pipelines",
        "Genomic analysis platforms", "AI for drug discovery", "Telemedicine platform development",
        "Remote patient monitoring systems", "Healthtech interoperability standards", "FHIR compliance solutions",
        "EdTech AI personalization", "Adaptive learning platforms", "Gamified corporate training",
        "Virtual classroom infrastructure", "AI-proctored examination systems", "Fintech fraud detection AI",
        "Algorithmic trading bot development", "RegTech compliance automation", "InsurTech claims processing AI",
        "Wealth management robo-advisors", "PropTech dynamic pricing models", "Smart building management systems",
        "Energy grid optimization AI", "Renewable energy forecasting tools", "Carbon footprint tracking software",
        "ESG reporting automation", "Sustainable supply chain verification", "Circular economy digital platforms",
        "Non-profit impact measurement", "NGO fundraising AI optimization", "Government digital service delivery",
        "Civic tech engagement platforms", "Smart simplified visa systems", "Digital identity verification (eKYC)",
        "Border control AI augmentation", "Disaster response coordination tools", "Humanitarian aid logistics AI",
        "Space tech data analysis", "Satellite imagery processing", "Maritime logistics optimization",
        "Autonomous vehicle software stack", "Drone fleet management systems", "Smart traffic control AI"
    ],
    localMarket: [
        "mobile app development", "web development sri lanka", "cheap web development", "ecommerce website development",
        "software development company", "website development company sri lanka", "best web developers in sri lanka",
        "app development sri lanka", "custom software development", "it company sri lanka", "web design sri lanka",
        "website designers in sri lanka", "seo services sri lanka", "digital marketing sri lanka", "social media marketing sri lanka",
        "wordpress development sri lanka", "react js developer sri lanka", "flutter app development", "android app development sri lanka",
        "ios app development sri lanka", "ui ux design sri lanka", "erp software sri lanka", "crm software sri lanka",
        "pos system sri lanka", "school management system sri lanka", "hospital management system sri lanka",
        "inventory management system sri lanka", "accounting software sri lanka", "hr management system sri lanka",
        "payroll system sri lanka", "booking system development", "custom web applications", "laravel development sri lanka",
        "php developers sri lanka", "node js development sri lanka", "python developers sri lanka", "software company colombo",
        "web development company colombo", "best it company in sri lanka", "startup software development", "saas development company",
        "website redesign sri lanka", "responsive web design sri lanka", "corporate website development", "landing page design sri lanka",
        "google ads management sri lanka", "facebook ads sri lanka", "technical seo sri lanka", "local seo sri lanka",
        "seo company colombo", "branding agency sri lanka", "logo design sri lanka", "graphic design sri lanka",
        "content marketing sri lanka", "email marketing sri lanka", "automation software sri lanka", "cloud software solutions",
        "api development sri lanka", "payment gateway integration sri lanka", "chatbot development sri lanka",
        "ai software development sri lanka", "machine learning sri lanka", "cyber security sri lanka", "web hosting sri lanka",
        "domain registration sri lanka", "website maintenance sri lanka", "software outsourcing sri lanka",
        "offshore development sri lanka", "custom crm development", "custom erp development", "real estate website development",
        "travel website development", "hotel booking system sri lanka", "restaurant website development",
        "ecommerce development sri lanka", "shopify development sri lanka", "woocommerce development sri lanka",
        "magento development sri lanka", "it solutions sri lanka", "best software company sri lanka",
        "professional web design sri lanka", "small business website sri lanka", "enterprise software development",
        "digital transformation sri lanka", "business automation sri lanka", "mobile app developers colombo",
        "web application development sri lanka", "progressive web app sri lanka", "full stack developers sri lanka",
        "frontend developers sri lanka", "backend developers sri lanka", "custom website sri lanka",
        "b2b software development", "b2c web development", "software consultancy sri lanka", "it consulting sri lanka",
        "technology partner sri lanka", "system integration sri lanka", "database development sri lanka",
        "cloud migration sri lanka", "aws development sri lanka", "azure development sri lanka", "google cloud sri lanka",
        "devops services sri lanka", "software testing sri lanka", "qa services sri lanka", "it support services sri lanka",
        "managed it services sri lanka", "outsourced it services sri lanka", "custom mobile apps sri lanka",
        "app developers colombo", "best web agency sri lanka", "digital agency sri lanka", "online marketing sri lanka",
        "search engine optimization sri lanka", "seo expert sri lanka", "ppc services sri lanka", "conversion optimization sri lanka",
        "lead generation sri lanka", "web analytics sri lanka", "software maintenance sri lanka", "website support sri lanka",
        "custom portal development", "client portal development", "membership website sri lanka", "booking app development",
        "ecommerce mobile app", "multi vendor ecommerce sri lanka", "marketplace development sri lanka", "custom cms development",
        "headless cms sri lanka", "api integration sri lanka", "third party integration sri lanka", "payment integration sri lanka",
        "sms gateway integration sri lanka", "whatsapp integration sri lanka", "erp implementation sri lanka",
        "crm implementation sri lanka", "software development colombo", "web development agency sri lanka",
        "mobile app company sri lanka", "custom system development", "online store development sri lanka",
        "shop website sri lanka", "corporate web design sri lanka", "best web designers colombo", "it services sri lanka",
        "technology company sri lanka", "software engineers sri lanka", "freelance web developer sri lanka",
        "freelance app developer sri lanka", "startup tech company sri lanka", "innovation company sri lanka",
        "digital solutions sri lanka", "online business solutions sri lanka", "enterprise web solutions",
        "modern web design sri lanka", "secure web development sri lanka", "fast website development",
        "high performance websites sri lanka", "custom dashboards sri lanka", "reporting system sri lanka",
        "data analytics sri lanka", "business intelligence sri lanka", "ai chatbot sri lanka", "automation tools sri lanka",
        "custom workflow software", "document management system sri lanka", "e learning platform sri lanka",
        "online education system sri lanka", "school software sri lanka", "medical software sri lanka",
        "clinic management system sri lanka", "pharmacy software sri lanka", "logistics software sri lanka",
        "transport management system sri lanka", "fleet management system sri lanka", "construction software sri lanka",
        "manufacturing software sri lanka", "retail software sri lanka", "wholesale software sri lanka",
        "inventory software sri lanka", "finance software sri lanka", "custom billing system sri lanka",
        "subscription software sri lanka", "appointment booking system sri lanka", "event management software sri lanka",
        "ticket booking system sri lanka", "property management software sri lanka", "hotel management software sri lanka",
        "tourism software sri lanka", "travel agency software sri lanka", "online payment system sri lanka",
        "secure software development sri lanka", "enterprise it solutions sri lanka", "corporate software sri lanka",
        "best digital marketing company sri lanka", "performance marketing sri lanka", "online advertising sri lanka",
        "social media management sri lanka", "brand strategy sri lanka", "website optimization sri lanka",
        "web speed optimization sri lanka", "core web vitals optimization sri lanka", "technical web audit sri lanka",
        "website security sri lanka", "ssl installation sri lanka", "cloud hosting sri lanka", "dedicated server sri lanka",
        "vps hosting sri lanka", "wordpress hosting sri lanka", "ecommerce hosting sri lanka", "it outsourcing sri lanka",
        "software partner sri lanka", "tech startup sri lanka", "digital innovation sri lanka",
        "custom application development sri lanka", "bespoke software sri lanka", "tailor made software sri lanka",
        "scalable software solutions sri lanka", "future ready technology sri lanka", "software development Seeduwa",
        "web engineering Negombo", "IT consultation Seeduwa", "SeraNex Seeduwa", "tech studio Negombo",
        "recruitment automation Sri Lanka", "hiring software Seeduwa", "applicant tracking Negombo",
        "software development Ja-Ela", "web design Colombo", "IT services Ja-Ela", "custom software Colombo",
        "best software company Colombo", "best software company Ja-Ela", "app development Colombo",
        "app development Ja-Ela", "ERP solutions Sri Lanka", "CRM software Colombo", "ATS systems Ja-Ela",
        // New Competitive Keywords
        "online store sri lanka", "enterprise resource planning colombo", "custom erp development sri lanka",
        "software company sri lanka", "it company negombo ja-ela", "best software studio colombo",
        "business digitisation colombo", "sme software solutions sri lanka", "ui ux design sri lanka",
        "ai tools for small business sri lanka", "best next.js development agency in sri lanka",
        "custom saas development company sri lanka", "whatsapp automation software developers sri lanka"
    ],
    enterprise: [
        "best erp systems 2026", "sap erp software solutions", "oracle fusion cloud erp", "netsuite for enterprise",
        "custom erp development sri lanka", "enterprise asset management software", "supply chain optimization ai",
        "business intelligence dashboards colombo", "cloud based erp systems negombo", "manufacturing erp software"
    ],
    hrTech: [
        "top 10 applicant tracking systems", "best recruitment software 2026", "talent acquisition platform ai",
        "automated cv screening software", "staffing agency software colombo", "hr management system sri lanka",
        "payroll automation seeduwa", "attendance tracking system negombo", "workforce management tools"
    ],
    fintech: [
        "best accounting software for small business", "cloud bookkeeping solutions sri lanka", "online invoicing portal",
        "financial management software colombo", "custom billing systems ja-ela", "pos system for retail sri lanka",
        "inventory management software negombo", "quickbooks enterprise support sri lanka"
    ],
    security: [
        "best business antivirus 2026", "endpoint security solutions sri lanka", "cybersecurity consulting colombo",
        "network security services seeduwa", "malware protection for enterprise", "zero trust architecture consulting",
        "data privacy compliance pdpa sri lanka", "secure cloud infrastructure"
    ],
    outsourcing: [
        "software outsourcing companies sri lanka", "custom software development agency colombo", "offshore development center sl",
        "hire dedicated developers sri lanka", "it staff augmentation colombo", "bespoke software engineering",
        "technology partner for startups", "software consultancy ja-ela"
    ]
};

export const SITE_METADATA = {
    title: "Seranex | Enterprise AI Engineering & High-Performance Software Studio",
    description: "Seranex is an elite software engineering studio specializing in autonomous AI agents, enterprise Next.js architectures, and scalable digital infrastructure. We build the future of automated business in Seeduwa, Negombo, Ja-Ela, and Colombo.",
    siteUrl: "https://seranex.org",
    twitterHandle: "@seranex_ai",
    ogImage: "/og-image.png",
    keywords: [
        ...SEO_KEYWORDS.tier1,
        ...SEO_KEYWORDS.tier2,
        ...SEO_KEYWORDS.authority,
        ...SEO_KEYWORDS.webDev,
        ...SEO_KEYWORDS.generated,
        ...SEO_KEYWORDS.localMarket,
        ...SEO_KEYWORDS.recruitment,
        ...SEO_KEYWORDS.enterprise,
        ...SEO_KEYWORDS.hrTech,
        ...SEO_KEYWORDS.fintech,
        ...SEO_KEYWORDS.security,
        ...SEO_KEYWORDS.outsourcing
    ].join(", ")
};

// Page-level SEO metadata helpers with advanced professional copy
export const PAGE_SEO = {
    home: {
        title: "Seranex | Best Software Company in Seeduwa, Negombo, Ja-Ela & Colombo",
        description: "Scale your enterprise with Seranex, the top-rated software studio in Sri Lanka. Expert AI Engineering, Custom ERP, and Next.js development across Seeduwa, Negombo, Ja-Ela, and Colombo.",
        image: "/og-image.png",
    },
    services: {
        title: "Custom Software & AI Solutions | Seeduwa, Negombo, Ja-Ela & Colombo",
        description: "Looking for a software company in Seeduwa, Negombo, Ja-Ela or Colombo? Seranex provides strategic engineering: AI agents, high-performance mobile apps, and enterprise SaaS systems.",
        keywords: "software company Colombo, web development Ja-Ela, AI solutions Sri Lanka, mobile app development Seeduwa, custom software Negombo, ERP software Colombo",
        image: "/og-image.png",
    },
    about: {
        title: "About Seranex | Elite Software Studio Serving Western Province",
        description: "Leading the digital transformation in Seeduwa, Negombo, Ja-Ela, and Colombo. Seranex bridges the gap between legacy logic and autonomous AI engineering for Sri Lankan enterprises.",
        keywords: "Seranex mission, software company Colombo, tech studio Ja-Ela, AI innovation Sri Lanka, digital sovereignty Colombo",
        image: "/og-image.png",
    },
    contact: {
        title: "Contact Seranex | Software Engineering Hub in Sri Lanka",
        description: "Connect with our engineers in Seeduwa. We serve clients across Negombo, Ja-Ela, and Colombo with high-level technical consultations on custom AI and software architecture.",
        keywords: "hire AI engineers Colombo, software consultation Ja-Ela, contact Seranex Sri Lanka, custom software development inquiry",
        image: "/og-image.png",
    },
    blog: {
        title: "Sera Insights | Agentic AI & Software Engineering in Sri Lanka",
        description: "Technical deep-dives into autonomous agents, Next.js performance, and the evolving landscape of enterprise software engineering in Colombo and beyond.",
        keywords: "AI blog Sri Lanka, technical software articles Colombo, Next.js performance tips, agentic AI research, SEO for 2026 Sri Lanka",
        image: "/og-image.png",
    },
    portfolio: {
        title: "Precision Engineering | Our Software Success Stories in Colombo & Negombo",
        description: "Explore our complex builds: high-performance e-commerce, AI logistics, and enterprise SaaS dashboards delivered to top clients in Colombo, Negombo, and Ja-Ela.",
        keywords: "software portfolio Sri Lanka, case studies AI Colombo, web development examples Negombo, enterprise dashboards Ja-Ela, mobile app projects Sri Lanka",
        image: "/og-image.png",
    },
    pricing: {
        title: "Investment Plans | Software Engineering Costs in Sri Lanka",
        description: "Transparent pricing for elite software engineering. TCO benchmarks for AI integration, custom web apps, and enterprise systems for Sri Lankan businesses.",
        keywords: "software development pricing Sri Lanka, AI implementation cost Colombo, enterprise software budget Negombo, custom software cost Ja-Ela",
        image: "/og-image.png",
    },
    quote: {
        title: "Request a Proposal | Custom Software Scoping in Colombo & Ja-Ela",
        description: "Provide your requirements and receive a comprehensive technical proposal for custom AI or software engineering in Colombo, Ja-Ela, or Negombo.",
        keywords: "project scope Colombo, software estimate Sri Lanka, AI automation proposal Ja-Ela, custom development quote Negombo",
        image: "/og-image.png",
    },
    privacy: {
        title: "Privacy & Data Governance | Seranex Sri Lanka",
        description: "Zero-trust security and data sovereignty in compliance with Sri Lankan PDPA and international standards.",
        image: "/og-image.png",
    },
    terms: {
        title: "Terms of Engineering | Seranex Service Standards",
        description: "Legal frameworks and professional service standards for Seranex projects in Sri Lanka and globally.",
        image: "/og-image.png",
    },
    legal: {
        title: "Legal & Regulatory Compliance | Seranex Global & Local Standards",
        description: "Regulatory framework guiding Seranex operations in Sri Lanka, focusing on international data standards and software liability.",
        image: "/og-image.png",
    },
    ats: {
        title: "AI Applicant Tracking System (ATS) | Elite Recruitment in Colombo & Ja-Ela",
        description: "Scale your workforce with the #1 AI-powered ATS in Colombo, Ja-Ela, Seeduwa, and Negombo. Automated CV screening and candidate scoring for Sri Lankan HR teams.",
        keywords: "ATS software Colombo, applicant tracking system Ja-Ela, recruitment automation Sri Lanka, hiring platform Negombo, HR tech Seeduwa",
        image: "/og-image.png",
    },
    // Dedicated Keyword Landing Pages
    onlineStore: {
        title: "Best Online Store Development in Sri Lanka | SeraNex",
        description: "Scale your retail business with elite online store development in Sri Lanka. High-performance e-commerce solutions built for speed, conversion, and global scale.",
        keywords: "online store sri lanka, ecommerce development sri lanka, shop website colombo, retail software sri lanka",
        image: "/og-image.png",
    },
    erpColombo: {
        title: "Enterprise Resource Planning (ERP) Colombo | Strategic Business Flow",
        description: "Leading ERP solutions in Colombo. SeraNex architects custom ERP systems for logistics, retail, and manufacturing in the Western Province commercial corridor.",
        keywords: "enterprise resource planning colombo, erp software sri lanka, business management system colombo, corporate software sri lanka",
        image: "/og-image.png",
    },
    customErp: {
        title: "Custom ERP Development Sri Lanka | Tailored Business Solutions",
        description: "Bespoke ERP development in Sri Lanka. We build mission-critical business infrastructure that automates workflows and scales with your enterprise.",
        keywords: "custom erp development sri lanka, bespoke erp software, enterprise automation sl, custom business software",
        image: "/og-image.png",
    },
    softwareCompanySL: {
        title: "Top Software Company Sri Lanka | Elite Engineering Studio",
        description: "Ranked as a top software company in Sri Lanka. SeraNex delivers cutting-edge AI, web, and mobile solutions for global and local enterprises.",
        keywords: "software company sri lanka, best it company colombo, software development studio sl, tech partners sri lanka",
        image: "/og-image.png",
    },
    itCompanyNegomboJaEla: {
        title: "IT Company Negombo & Ja-Ela | Local Tech Authority",
        description: "The premier IT company serving Negombo and Ja-Ela. We provide on-site technical consultations and high-end software engineering for regional businesses.",
        keywords: "it company negombo ja-ela, software company seeduwa, web development negombo, it services ja-ela",
        image: "/og-image.png",
    },
    softwareStudioColombo: {
        title: "Best Software Studio Colombo | High-Performance Engineering",
        description: "The best software studio in Colombo for AI and Next.js development. We engineer high-performance digital products for elite Sri Lankan brands.",
        keywords: "best software studio colombo, premium software development colombo, elite tech studio sl, software engineers colombo",
        image: "/og-image.png",
    },
    businessDigitisation: {
        title: "Business Digitisation Colombo | Modernise Your Operations",
        description: "Accelerate your digital transformation with business digitisation in Colombo. We bridge the gap between manual processes and automated AI logic.",
        keywords: "business digitisation colombo, digital transformation sri lanka, business automation colombo, paperless office sl",
        image: "/og-image.png",
    },
    smeSolutions: {
        title: "SME Software Solutions Sri Lanka | Affordable Enterprise Tech",
        description: "Professional software solutions for Sri Lankan SMEs. Scalable inventory, CRM, and accounting systems designed for small business growth.",
        keywords: "sme software solutions sri lanka, small business software sl, startup technology sri lanka, affordable erp sl",
        image: "/og-image.png",
    },
    uiuxDesign: {
        title: "UI UX Design Sri Lanka | Premium Digital Experiences",
        description: "Elite UI UX design in Sri Lanka. We create stunning, user-centric interfaces that convert visitors into customers for Colombo's leading enterprises.",
        keywords: "ui ux design sri lanka, best web design colombo, user experience agency sl, interface design sri lanka",
        image: "/og-image.png",
    },
    aiToolsSmallBusiness: {
        title: "AI Tools for Small Business Sri Lanka | Automate Your Growth",
        description: "Empower your small business with AI tools in Sri Lanka. Automated customer support, AI bookkeeping, and intelligent marketing assistants for local growth.",
        keywords: "ai tools for small business sri lanka, ai for startups sl, business automation ai, small business tech sl",
        image: "/og-image.png",
    },
    nextjsAgency: {
        title: "Best Next.js Development Agency in Sri Lanka | SeraNex",
        description: "The #1 Next.js development agency in Sri Lanka. We build high-performance, SEO-optimized web applications using the latest Next.js features (App Router, PPR, Turbopack).",
        keywords: "best next.js development agency in sri lanka, next.js developers colombo, high performance web apps sl, react agency sri lanka",
        image: "/og-image.png",
    },
    customSaas: {
        title: "Custom SaaS Development Company Sri Lanka | Scale Your Software",
        description: "Expert custom SaaS development in Sri Lanka. We architect multi-tenant, scalable, and secure cloud software for global and local startups.",
        keywords: "custom saas development company sri lanka, saas builders colombo, multi tenant software sl, cloud application development",
        image: "/og-image.png",
    },
    whatsappAutomation: {
        title: "WhatsApp Automation Software Developers Sri Lanka | SeraNex",
        description: "Leading WhatsApp automation developers in Sri Lanka. We build intelligent AI-powered WhatsApp bots and automation workflows to scale your sales and support.",
        keywords: "whatsapp automation software developers sri lanka, whatsapp chatbot colombo, business automation bots sl, ai messaging solutions",
        image: "/og-image.png",
    }
};
