export const SEO_KEYWORDS = {
    tier1: [
        // Standard Enterprise & SaaS
        "Custom AI & Agentic Software", "Autonomous AI agent development", "Enterprise agentic workflows",
        "Bespoke AI software solutions", "Multi-agent system architecture", "AI agent security frameworks",
        "Generative AI for enterprise", "Custom LLM fine-tuning services", "Autonomous digital employees",
        "AI-driven business process automation", "Goal-oriented AI agents", "AI agent pilot-to-production",
        "Scalable agentic commerce", "Agentic orchestration mesh", "Enterprise AI strategy consulting",
        "Custom AI chatbot for high-end retail", "AI-led legacy modernization", "Predictive maintenance AI agents",
        "AI-native software architecture", "Autonomous customer concierge", "B2B sales automation agents",
        "AI agent knowledge base grounding", "Secure AI implementation", "Global AI-powered data analytics dashboards",
        "Cognitive automation services", "Advanced RAG implementation",

        // Next-Gen Mobile & Web
        "Next.js 16 enterprise development", "React Native New Architecture migration", "High-performance cross-platform apps",
        "Fabric renderer optimization", "TurboModules implementation", "Next.js PPR for e-commerce",
        "Server-side rendering mobile apps", "React Native JSI C++ development", "Universal app engineering",
        "Zero-bridge React Native apps", "Scalable SaaS dashboard", "Next.js Enterprise mobile security standards",
        "Custom visionOS spatial apps", "Next.js Turbopack build optimization", "React Native shadow tree optimization",
        "Multi-tenant SaaS architecture", "Next.js 16 developer for hire", "Performance-first mobile engineering",
        "Progressive Web Apps enterprise", "Cloud-native mobile backends",

        // Custom Software & Outsourcing
        "Custom software development 2026", "Offshore AI engineering team", "Global Capability Center as a Service",
        "Build-Operate-Transfer software model", "Bespoke ERP development", "Digital sovereignty cloud solutions",
        "Intelligent process automation", "Custom CRM for regulated industries", "Legacy system digital transformation",
        "Outcome-based software contracts", "Software staff augmentation AI", "Enterprise-grade low-code integration",
        "Resilient digital architecture", "Agile software development global", "Full-stack engineering services",
        "Cloud migration for enterprise", "API-first software development", "Dedicated software development team",
        "Custom fintech software solutions", "Microservices architecture design"
    ],
    tier2: [
        // Local Business & AI Automation
        "Business automation software Sri Lanka", "AI solutions for Sri Lankan corporates", "Enterprise AI company Colombo",
        "Custom AI software development Sri Lanka", "Sera Auto business automation", "SME digital transformation Sri Lanka",
        "AI for Sri Lankan banking and finance", "Digital modernization services Colombo", "AI-powered customer support Sri Lanka",
        "Automated accounting software Sri Lanka", "Data-driven decision making tools SL", "Sri Lanka AI strategy partners",
        "Top ICT company in Sri Lanka", "AI for Sri Lankan manufacturing sector", "Corporate AI training and implementation",

        // Local Mobile & Software Development
        "Mobile app development Sri Lanka", "Best mobile app company Colombo", "Android and iOS developers Sri Lanka",
        "React Native app development Colombo", "Next.js developer Sri Lanka", "Custom software company Sri Lanka",
        "Enterprise mobile apps Colombo", "E-commerce app development Sri Lanka", "Mobile banking app security SL",
        "Fintech app developers Sri Lanka", "Custom CRM software Sri Lanka", "HR management system Sri Lanka",
        "Payroll software Sri Lanka", "ERP system development Sri Lanka", "Inventory management software SL",
        "Web application development Colombo", "Software outsourcing Sri Lanka", "IT consulting services Colombo",
        "PDPA compliant software development SL", "Cloud migration services Sri Lanka",
        "Software company Seeduwa", "Software company Negombo", "Web development Seeduwa", "Web development Negombo",
        "Best IT company Seeduwa", "Custom software Negombo", "AI solutions Seeduwa"
    ],
    authority: [
        // International SEO & Authority
        "Generative Engine Optimization services", "Optimize website for AI Overviews", "AI citation authority branding",
        "Rank in ChatGPT search 2026", "Structured data for AI agent crawling", "AI-first content marketing",
        "Voice search optimization enterprise", "Technical SEO for agentic discovery", "Conversational keyword research",
        "Brand presence in AI search", "LLM citation and referral optimization", "Semantic mapping for search",
        "GEO strategy for software firms", "Predictive SEO analytics", "Automated SEO audit AI agents"
    ],
    // Web Development Core Keywords
    webDev: [
        // Core Industry Keywords
        "Web development company", "Web development services", "Custom web development",
        "Web application development", "Website design and development", "Website developer",
        "Web design agency", "Professional web development", "Full-service web development",
        "Web development firm", "Web development solutions",

        // Service-Specific & Technology
        "Ecommerce web development company", "Responsive web design", "Frontend development",
        "Backend developer", "WordPress website creation", "Shopify web design agency",
        "Progressive Web Application PWA", "React web development", "Node.js web development",
        "Custom ecommerce development", "Headless CMS development", "JAMstack development services",
        "TypeScript development company", "Tailwind CSS development", "UI UX design services",
        "Single page application development",

        // Long-Tail & High-Intent
        "Best web design company", "Custom software development services", "Hire web developers",
        "Website maintenance services", "API development company", "Best web development agency near me",
        "Affordable web development services", "Enterprise web application development",
        "Custom website design for startups", "E-commerce website development cost",
        "Web development company for small business", "Web application security services",
        "Website redesign services", "Landing page design services", "Web development consultation",
        "Full stack web developer for hire", "Website performance optimization services",
        "Cross-platform web development", "Cloud-based web application development",
        "SaaS web application development", "Web development outsourcing company",
    ],
    generated: [
        "AI-powered logistics optimization", "Neural network consulting", "Deep learning for healthcare",
        "Computer vision systems integration", "Natural language processing for legal tech", "AI ethics compliance auditing",
        "Automated code generation tools", "Self-healing infrastructure automation", "AI-driven supply chain resilience",
        "Hyper-personalized marketing AI", "Robotic Process Automation (RPA) 2.0", "Edge AI implementation services",
        "Federated learning solutions", "Explainable AI (XAI) consulting", "AI model governance frameworks",
        "Synthetic data generation for training", "Digital twin development services", "Smart city AI infrastructure",
        "Precision agriculture AI solutions", "AI-enhanced cybersecurity defense", "Quantum-resistant cryptography integration",
        "Blockchain-AI convergence solutions", "Decentralized AI marketplaces", "Web3 autonomous organizations (DAOs)",
        "Metaverse enterprise solutions", "Immersive commerce experiences", "Haptic technology integration",
        "Brain-computer interface (BCI) apps", "Neuromorphic computing software", "Bioinformatics data pipelines",
        "Genomic analysis platforms", "AI for drug discovery", "Telemedicine platform development",
        "Remote patient monitoring systems", "Healthtech interoperability standards", "FHIR compliance solutions",
        "EdTech AI personalization", "Adaptive learning platforms", "Gamified corporate training",
        "Virtual classroom infrastructure", "AI-proctored examination systems", "Fintech fraud detection AI",
        "Algorithmic trading bot development", "RegTech compliance automation", "InsurTech claims processing AI",
        "Wealth management robo-advisors", "PropTech dynamic pricing models", "Smart building management systems",
        "Energy grid optimization AI", "Renewable energy forecasting tools", "Carbon footprint tracking software",
        "ESG reporting automation", "Sustainable supply chain verification", "Circular economy digital platforms",
        "Non-profit impact measurement", "NGO fundraising AI optimization", "Government digital service delivery",
        "Civic tech engagement platforms", "Smart simplified visa systems", "Digital identity verification (eKYC)",
        "Border control AI augmentation", "Disaster response coordination tools", "Humanitarian aid logistics AI",
        "Space tech data analysis", "Satellite imagery processing", "Maritime logistics optimization",
        "Autonomous vehicle software stack", "Drone fleet management systems", "Smart traffic control AI"
    ],
    localMarket: [
        "mobile app development", "web development sri lanka", "cheap web development", "ecommerce website development",
        "software development company", "website development company sri lanka", "best web developers in sri lanka",
        "app development sri lanka", "custom software development", "it company sri lanka", "web design sri lanka",
        "website designers in sri lanka", "seo services sri lanka", "digital marketing sri lanka", "social media marketing sri lanka",
        "wordpress development sri lanka", "react js developer sri lanka", "flutter app development", "android app development sri lanka",
        "ios app development sri lanka", "ui ux design sri lanka", "erp software sri lanka", "crm software sri lanka",
        "pos system sri lanka", "school management system sri lanka", "hospital management system sri lanka",
        "inventory management system sri lanka", "accounting software sri lanka", "hr management system sri lanka",
        "payroll system sri lanka", "booking system development", "custom web applications", "laravel development sri lanka",
        "php developers sri lanka", "node js development sri lanka", "python developers sri lanka", "software company colombo",
        "web development company colombo", "best it company in sri lanka", "startup software development", "saas development company",
        "website redesign sri lanka", "responsive web design sri lanka", "corporate website development", "landing page design sri lanka",
        "google ads management sri lanka", "facebook ads sri lanka", "technical seo sri lanka", "local seo sri lanka",
        "seo company colombo", "branding agency sri lanka", "logo design sri lanka", "graphic design sri lanka",
        "content marketing sri lanka", "email marketing sri lanka", "automation software sri lanka", "cloud software solutions",
        "api development sri lanka", "payment gateway integration sri lanka", "chatbot development sri lanka",
        "ai software development sri lanka", "machine learning sri lanka", "cyber security sri lanka", "web hosting sri lanka",
        "domain registration sri lanka", "website maintenance sri lanka", "software outsourcing sri lanka",
        "offshore development sri lanka", "custom crm development", "custom erp development", "real estate website development",
        "travel website development", "hotel booking system sri lanka", "restaurant website development",
        "ecommerce development sri lanka", "shopify development sri lanka", "woocommerce development sri lanka",
        "magento development sri lanka", "it solutions sri lanka", "best software company sri lanka",
        "professional web design sri lanka", "small business website sri lanka", "enterprise software development",
        "digital transformation sri lanka", "business automation sri lanka", "mobile app developers colombo",
        "web application development sri lanka", "progressive web app sri lanka", "full stack developers sri lanka",
        "frontend developers sri lanka", "backend developers sri lanka", "custom website sri lanka",
        "b2b software development", "b2c web development", "software consultancy sri lanka", "it consulting sri lanka",
        "technology partner sri lanka", "system integration sri lanka", "database development sri lanka",
        "cloud migration sri lanka", "aws development sri lanka", "azure development sri lanka", "google cloud sri lanka",
        "devops services sri lanka", "software testing sri lanka", "qa services sri lanka", "it support services sri lanka",
        "managed it services sri lanka", "outsourced it services sri lanka", "custom mobile apps sri lanka",
        "app developers colombo", "best web agency sri lanka", "digital agency sri lanka", "online marketing sri lanka",
        "search engine optimization sri lanka", "seo expert sri lanka", "ppc services sri lanka", "conversion optimization sri lanka",
        "lead generation sri lanka", "web analytics sri lanka", "software maintenance sri lanka", "website support sri lanka",
        "custom portal development", "client portal development", "membership website sri lanka", "booking app development",
        "ecommerce mobile app", "multi vendor ecommerce sri lanka", "marketplace development sri lanka", "custom cms development",
        "headless cms sri lanka", "api integration sri lanka", "third party integration sri lanka", "payment integration sri lanka",
        "sms gateway integration sri lanka", "whatsapp integration sri lanka", "erp implementation sri lanka",
        "crm implementation sri lanka", "software development colombo", "web development agency sri lanka",
        "mobile app company sri lanka", "custom system development", "online store development sri lanka",
        "shop website sri lanka", "corporate web design sri lanka", "best web designers colombo", "it services sri lanka",
        "technology company sri lanka", "software engineers sri lanka", "freelance web developer sri lanka",
        "freelance app developer sri lanka", "startup tech company sri lanka", "innovation company sri lanka",
        "digital solutions sri lanka", "online business solutions sri lanka", "enterprise web solutions",
        "modern web design sri lanka", "secure web development sri lanka", "fast website development",
        "high performance websites sri lanka", "custom dashboards sri lanka", "reporting system sri lanka",
        "data analytics sri lanka", "business intelligence sri lanka", "ai chatbot sri lanka", "automation tools sri lanka",
        "custom workflow software", "document management system sri lanka", "e learning platform sri lanka",
        "online education system sri lanka", "school software sri lanka", "medical software sri lanka",
        "clinic management system sri lanka", "pharmacy software sri lanka", "logistics software sri lanka",
        "transport management system sri lanka", "fleet management system sri lanka", "construction software sri lanka",
        "manufacturing software sri lanka", "retail software sri lanka", "wholesale software sri lanka",
        "inventory software sri lanka", "finance software sri lanka", "custom billing system sri lanka",
        "subscription software sri lanka", "appointment booking system sri lanka", "event management software sri lanka",
        "ticket booking system sri lanka", "property management software sri lanka", "hotel management software sri lanka",
        "tourism software sri lanka", "travel agency software sri lanka", "online payment system sri lanka",
        "secure software development sri lanka", "enterprise it solutions sri lanka", "corporate software sri lanka",
        "best digital marketing company sri lanka", "performance marketing sri lanka", "online advertising sri lanka",
        "social media management sri lanka", "brand strategy sri lanka", "website optimization sri lanka",
        "web speed optimization sri lanka", "core web vitals optimization sri lanka", "technical web audit sri lanka",
        "website security sri lanka", "ssl installation sri lanka", "cloud hosting sri lanka", "dedicated server sri lanka",
        "vps hosting sri lanka", "wordpress hosting sri lanka", "ecommerce hosting sri lanka", "it outsourcing sri lanka",
        "software partner sri lanka", "tech startup sri lanka", "digital innovation sri lanka",
        "custom application development sri lanka", "bespoke software sri lanka", "tailor made software sri lanka",
        "scalable software solutions sri lanka", "future ready technology sri lanka", "software development Seeduwa",
        "web engineering Negombo", "IT consultation Seeduwa", "SeraNex Seeduwa", "tech studio Negombo"
    ]
};

export const SITE_METADATA = {
    title: "Seranex | Enterprise AI Engineering & High-Performance Software Studio",
    description: "Seranex is an elite software engineering studio specializing in autonomous AI agents, enterprise Next.js architectures, and scalable digital infrastructure. We build the future of automated business.",
    siteUrl: "https://seranex.org",
    twitterHandle: "@seranex_ai",
    ogImage: "/og-image.png",
    keywords: [
        ...SEO_KEYWORDS.tier1,
        ...SEO_KEYWORDS.tier2,
        ...SEO_KEYWORDS.authority,
        ...SEO_KEYWORDS.webDev,
        ...SEO_KEYWORDS.generated,
        ...SEO_KEYWORDS.localMarket
    ].join(", ")
};

// Page-level SEO metadata helpers with advanced professional copy
export const PAGE_SEO = {
    home: {
        title: "Seranex | Best Software Company in Seeduwa & Negombo | AI Engineering",
        description: "Scale your enterprise with Seranex, the top-rated software studio in Seeduwa and Negombo. We specialize in Agentic AI, custom RAG architectures, and high-performance Next.js systems.",
        image: "/og-image.png",
    },
    services: {
        title: "Custom Web & Mobile Development Seeduwa | AI Solutions Negombo",
        description: "Looking for a software company in Seeduwa or Negombo? Seranex provides strategic engineering: AI agents, high-performance mobile apps, and enterprise SaaS systems optimized for local and global scale.",
        keywords: "software company Seeduwa, web development Negombo, AI solutions Sri Lanka, mobile app development Seeduwa, custom software Negombo",
        image: "/og-image.png",
    },
    about: {
        title: "About Seranex | Elite Software Studio in Seeduwa & Negombo",
        description: "Headquartered in Seeduwa, Seranex is bridging the gap between legacy business logic and autonomous AI. We are the premier choice for custom software in Negombo and the Gampaha district.",
        keywords: "Seranex mission, software company Seeduwa, tech studio Negombo, AI innovation Sri Lanka, digital sovereignty",
        image: "/og-image.png",
    },
    contact: {
        title: "Consult with Our Engineers | Build Your Next Enterprise Solution",
        description: "Ready to automate your operations with AI? Contact Seranex for a high-level technical consultation on custom software, AI agents, and enterprise-grade web architectures.",
        keywords: "hire AI engineers, software consultation Colombo, contact Seranex, custom software development inquiry",
        image: "/og-image.png",
    },
    blog: {
        title: "Sera Insights | The Future of Agentic AI & Performance Web",
        description: "Technical deep-dives into the era of autonomous agents, Core Web Vitals dominance, and the evolving landscape of enterprise software engineering in 2026.",
        keywords: "AI blog, technical software articles, Next.js performance tips, agentic AI research, SEO for 2026",
        image: "/og-image.png",
    },
    portfolio: {
        title: "Precision Engineering | Our Custom Software & AI Work",
        description: "Explore a curated showcase of our most complex builds: high-performance e-commerce engines, AI-powered logistics platforms, and enterprise-grade SaaS dashboards.",
        keywords: "software portfolio, case studies AI, web development examples, enterprise dashboards, mobile app projects",
        image: "/og-image.png",
    },
    pricing: {
        title: "Strategic Investment | Transparent Software Engineering Plans",
        description: "Clear, value-driven pricing for elite software engineering. Discover total cost of ownership (TCO) benchmarks for AI integration, custom web apps, and enterprise systems.",
        keywords: "software development pricing, TCO analysis, AI implementation cost, enterprise software budget",
        image: "/og-image.png",
    },
    quote: {
        title: "Request a Technical Proposal | Precise Project Scoping",
        description: "Detailed scoping for your next digital asset. Provide your business requirements and receive a comprehensive technical proposal for custom AI or software engineering.",
        keywords: "project scope, software estimate, AI automation proposal, custom development quote",
        image: "/og-image.png",
    },
    privacy: {
        title: "Privacy & Data Governance | Seranex Safety First",
        description: "Our commitment to zero-trust security and data sovereignty. Learn how we handle enterprise data with the highest standards of encryption and privacy compliance.",
        image: "/og-image.png",
    },
    terms: {
        title: "Terms of Engineering | Service Standards & Protocols",
        description: "Legal frameworks and professional service standards for Seranex projects. Understanding our commitment to code quality, IP ownership, and project delivery.",
        image: "/og-image.png",
    },
    legal: {
        title: "Legal & Regulatory Compliance | Seranex Global Standards",
        description: "The regulatory framework guiding Seranex operations, focusing on international data standards and software liability protections.",
        image: "/og-image.png",
    }
};
